[providers]
nodejs = false

[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn --timeout 120 blog_app:app"
